src/App.jsx
src/Home.jsx
src/api.js
src/constants/variables.js
src/subsets/Aggregations.jsx
src/subsets/CheckboxContainer.jsx
src/subsets/Geography.jsx
src/subsets/Subsets.css
src/subsets/Subsets.jsx
src/subsets/selectUtils.js

CSV endpoints are currently non-functional afaict, but the data download is pointing to the right endpoint.

Data by geography and subsets

---

src/constants/variables.js

add integers to labels

---

src/api.js
src/common/Alert.css
src/common/Alert.jsx
src/subsets/Aggregations.jsx
src/subsets/Error.jsx
src/subsets/Geography.jsx
src/subsets/Subsets.css
src/subsets/Subsets.jsx

Fixes key bug and introduces error handling
Closes #12

Key bugfix

---

src/constants/variables.js

Add additional vars

---

src/subsets/Subsets.css
src/subsets/Subsets.jsx

Total row advisory

---

src/query.js
src/subsets/Subsets.jsx

Check valid keys and values & regenerate search

---

src/api.js

switch to standard backend endpoint

---

src/constants/variables.js

Change ethnicities to ethnicity in variables constant

---

src/geo/CheckboxContainer.jsx
src/geo/Geography.css
src/geo/Geography.jsx

Both to stop current confusion and to clear the way for more than two variables
Closes #58

Don't render checkboxcontainer placeholders

---

src/geo/Aggregations.jsx

Format with commas

---

src/api.js

Add hardcoded years param to all api calls

---

src/app.css
src/geo/Geography.jsx

Add and style link to homepage

---

src/geo/Geography.css

fix aggregation total alignment for left aligned button

---

src/common/LoadingIcon.css
src/geo/Geography.jsx
src/geo/LoadingButton.jsx

Add loading icon to details button

---

src/geo/Geography.jsx

Fix nationwide mapping bug

---

src/geo/Geography.jsx

Clear errors on requestSubset

---

src/geo/Geography.jsx

change field count

---

src/Home.jsx

rewrite homepage intro language

---

src/Home.jsx
src/ImageCard.jsx

remove images from homepage links

---

src/geo/Geography.jsx

remove entire from dataset download button

---

src/geo/Aggregations.jsx
src/geo/Geography.jsx

pass ref to aggregation table and scroll it into view 

---

src/geo/Error.jsx

fix error message typo

---

src/constants/variables.js

added sex not available option

---

kubernetes/beta/hmda-data-browser/templates/service.yaml

update ambassador config so data browser points to home-page

update ambassador config

---

src/geo/Aggregations.jsx
src/geo/Geography.css
src/geo/Geography.jsx

Closes #112 
- Changes the way the table is structured and designed to allow unlimited selection of variables
- Enhances the layout of various elements to look coherent under any number of variables
- Sorts the table values alphabetically on each selected variable

Unlimited variables

---

src/geo/Geography.jsx

Reintroduce two variable limit

---

src/constants/variables.js

Closes #138 based on https://github.com/cfpb/hmda-platform/issues/2997

Fix race name

---

src/constants/variables.js

change variable order

---

src/api.js

Firefox issue

---

src/Beta.jsx
src/geo/Geography.jsx

update feedback email

---

src/Beta.jsx
src/geo/Aggregations.jsx
src/geo/Geography.jsx
src/geo/GeographySelect.jsx
src/geo/VariableSelect.jsx
src/geo/selectUtils.js
src/query.js
src/query.test.js

Geo refactor

---

src/Beta.jsx
src/Header.jsx
src/Home.jsx
src/geo/Aggregations.jsx
src/geo/DocLink.jsx
src/geo/Geography.jsx
src/geo/GeographySelect.jsx
src/geo/VariableSelect.jsx
src/geo/selectUtils.js
src/query.js
src/query.test.js

Hardlink doc

---

src/geo/Geography.jsx

Closes https://github.com/cfpb/hmda-data-browser/issues/193

Show file size warning for Nationwide

---

src/constants/stateObj.js
src/geo/ItemSelect.jsx
src/geo/selectUtils.js

Content updates

---

src/geo/ActionsWarningsErrors.jsx
src/geo/Aggregations.jsx
src/geo/Geography.css
src/geo/Geography.jsx
src/geo/Geography.test.js
src/geo/InstitutionSelect.jsx
src/geo/InstitutionSelect.test.js
src/geo/ItemSelect.jsx
src/geo/LoadingButton.jsx
src/geo/VariableSelect.jsx
src/geo/selectUtils.js

Closes #209 
Updates workflow to
- always show all selections
- download the most specific dataset available based on user inputs
- include new guiding language

Updated user workflow
